### ISSUE TITLE
is it possible to change the created username from AccountName to userPrincipalName?

### ISSUE THREAD

**Issue by betonmoewe** [Takalele/phpipam_directory_sync#1]
First of all, thank you very much for this very useful extension of phpipam! 
but now to my question: what would have to be changed to derive the username not from accountName but from PrincipalName? The background is that this would make it easier to standardise the login (otherwise I have linux applications that also need the domain when logging in (to distinguish more clearly whether local account or AD account)).

Best regards

Betonmoewe

**Comment by Takalele** [comment]
Hi @betonmoewe!

Thank you, I'm glad you find the extension useful!

Regarding your question: The current implementation relies on the internal PHPIPAM modules and functions, which are designed to use the samaccountname for authentication. To switch to using the PrincipalName instead, PHPIPAM itself would need to be modified, specifically in the [adLDAP](https://github.com/phpipam/phpipam/tree/95d106d014de9088734d551f65adaa3bc56fc7eb/functions/adLDAP) module. This module handles the interaction with Active Directory, and adjustments would be necessary there.

If PHPIPAM supports PrincipalName, the script should work without any modifications.

Best regards,
Takalele
